FROM node:20-alpine3.19

# WORKDIR /product-service
WORKDIR /product-service

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install && npm install -g nodemon

# Copy other file
COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src
COPY tsoa.json ./

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD [ "npm","run","dev" ]

# url store in mongodb, image store in s3/remote server
# clude dinary
# compose-docker for manage doocker container contain mongdb

# ចាប់file to upload អោយបាន
# យកទៅStore in server
# https://dev.to/collegewap/how-to-save-images-to-mongodb-in-nodejs-dog